# AGW

In [2]:
# R_S_to_L
# source domain: Regdb, SYSU
# unseen domain: LLCM
%run train.py --protocol R_S_to_L

trainset: RegDB, SYSU
testset: LLCM
Args:Namespace(arch='resnet50', batch_size=8, dataset='sysu', gpu='0', img_h=288, img_w=144, log_path='log/', lr=0.1, margin=0.3, max_epoch=30, method='agw', mode='all', model_path='save_model/', num_pos=4, optim='sgd', protocol='R_S_to_L', resume='', save_epoch=20, seed=0, test_batch=64, test_only=False, trial=1, vis_log_path='log/vis_log/', workers=4)
==> Loading data..


Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%|██████████| 97.8M/97.8M [00:08<00:00, 12.0MB/s]


==> Start Training...
==> Preparing Data Loader...
0
[24232 24236 24229 ... 23701 23698 23696]
[13883 13869 13881 ... 13364 13351 13362]


/root/autodl-tmp/AGW/loss.py:121: UserWarning: This overload of addmm_ is deprecated:
	addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
	addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1485.)
  dist_mtx = dist_mtx.addmm_(1, -2, emb1, emb2.t())


Epoch: [0][0/759] Time: 2.739 (2.739) lr:0.010 Loss: 40.1745 (40.1745) iLoss: 6.3884 (6.3884) TLoss: 33.7861 (33.7861) Accu: 0.00
Epoch: [0][50/759] Time: 0.142 (0.194) lr:0.010 Loss: 6.6300 (15.3341) iLoss: 5.9771 (6.2681) TLoss: 0.6528 (9.0659) Accu: 14.34
Epoch: [0][100/759] Time: 0.145 (0.169) lr:0.010 Loss: 6.1962 (10.8758) iLoss: 5.5994 (5.9947) TLoss: 0.5968 (4.8811) Accu: 26.13
Epoch: [0][150/759] Time: 0.146 (0.161) lr:0.010 Loss: 6.3530 (9.1436) iLoss: 5.7737 (5.6877) TLoss: 0.5793 (3.4559) Accu: 33.02
Epoch: [0][200/759] Time: 0.143 (0.157) lr:0.010 Loss: 3.9446 (8.1367) iLoss: 3.4321 (5.4060) TLoss: 0.5124 (2.7307) Accu: 37.80
Epoch: [0][250/759] Time: 0.144 (0.154) lr:0.010 Loss: 3.4548 (7.3932) iLoss: 2.9301 (5.1015) TLoss: 0.5247 (2.2916) Accu: 41.81
Epoch: [0][300/759] Time: 0.144 (0.153) lr:0.010 Loss: 4.4913 (6.8349) iLoss: 3.9242 (4.8384) TLoss: 0.5671 (1.9965) Accu: 45.01
Epoch: [0][350/759] Time: 0.147 (0.152) lr:0.010 Loss: 4.1118 (6.3681) iLoss: 3.6361 (4.5889) T

In [1]:
# R_L_to_S
# source domain: Regdb, LLCM
# unseen domain: SYSU
%run train.py --protocol R_L_to_S

trainset: RegDB, LLCM
testset: SYSU
Args:Namespace(arch='resnet50', batch_size=8, dataset='sysu', gpu='0', img_h=288, img_w=144, log_path='log/', lr=0.1, margin=0.3, max_epoch=30, method='agw', mode='all', model_path='save_model/', num_pos=4, optim='sgd', protocol='R_L_to_S', resume='', save_epoch=20, seed=0, test_batch=64, test_only=False, trial=1, vis_log_path='log/vis_log/', workers=4)
==> Loading data..
==> Start Training...
==> Preparing Data Loader...
0
[ 4899  4894  4914 ... 18600 18591 18603]
[ 4074  4075  4075 ... 15741 15744 15752]


/root/autodl-tmp/AGW/loss.py:121: UserWarning: This overload of addmm_ is deprecated:
	addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
	addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1485.)
  dist_mtx = dist_mtx.addmm_(1, -2, emb1, emb2.t())


Epoch: [0][0/593] Time: 2.718 (2.718) lr:0.010 Loss: 38.5258 (38.5258) iLoss: 6.8301 (6.8301) TLoss: 31.6957 (31.6957) Accu: 0.00
Epoch: [0][50/593] Time: 0.148 (0.196) lr:0.010 Loss: 7.3968 (16.3075) iLoss: 6.7794 (6.7605) TLoss: 0.6174 (9.5470) Accu: 16.91
Epoch: [0][100/593] Time: 0.145 (0.171) lr:0.010 Loss: 6.1911 (11.6592) iLoss: 5.5540 (6.5425) TLoss: 0.6371 (5.1168) Accu: 29.77
Epoch: [0][150/593] Time: 0.145 (0.162) lr:0.010 Loss: 7.6663 (9.8987) iLoss: 7.0695 (6.2889) TLoss: 0.5968 (3.6099) Accu: 35.47
Epoch: [0][200/593] Time: 0.145 (0.158) lr:0.010 Loss: 6.4932 (8.9306) iLoss: 6.0043 (6.0819) TLoss: 0.4889 (2.8488) Accu: 39.16
Epoch: [0][250/593] Time: 0.147 (0.156) lr:0.010 Loss: 5.0853 (8.2311) iLoss: 4.5158 (5.8457) TLoss: 0.5695 (2.3854) Accu: 42.17
Epoch: [0][300/593] Time: 0.145 (0.154) lr:0.010 Loss: 5.5395 (7.6988) iLoss: 4.9397 (5.6250) TLoss: 0.5998 (2.0738) Accu: 44.56
Epoch: [0][350/593] Time: 0.147 (0.153) lr:0.010 Loss: 4.6179 (7.2245) iLoss: 4.0464 (5.3763) T

In [1]:
# L_S_to_R
# source domain: LLCM, SYSU
# unseen domain: RegDB
%run train.py --protocol L_S_to_R

trainset: LLCM, SYSU
testset: RegDB
Args:Namespace(arch='resnet50', batch_size=8, dataset='sysu', gpu='0', img_h=288, img_w=144, log_path='log/', lr=0.1, margin=0.3, max_epoch=30, method='agw', mode='all', model_path='save_model/', num_pos=4, optim='sgd', protocol='L_S_to_R', resume='', save_epoch=20, seed=0, test_batch=64, test_only=False, trial=1, vis_log_path='log/vis_log/', workers=4)
==> Loading data..
==> Start Training...
==> Preparing Data Loader...
0
[38038 38032 38038 ... 37674 37675 37678]
[24738 24733 24725 ... 24366 24373 24378]


/root/autodl-tmp/AGW/loss.py:121: UserWarning: This overload of addmm_ is deprecated:
	addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
	addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1485.)
  dist_mtx = dist_mtx.addmm_(1, -2, emb1, emb2.t())


Epoch: [0][0/1225] Time: 2.623 (2.623) lr:0.010 Loss: 39.8666 (39.8666) iLoss: 7.0004 (7.0004) TLoss: 32.8662 (32.8662) Accu: 0.00
Epoch: [0][50/1225] Time: 0.143 (0.193) lr:0.010 Loss: 7.5745 (15.8365) iLoss: 6.9185 (6.9441) TLoss: 0.6561 (8.8924) Accu: 13.48
Epoch: [0][100/1225] Time: 0.144 (0.169) lr:0.010 Loss: 6.7372 (11.6347) iLoss: 6.1299 (6.8268) TLoss: 0.6073 (4.8079) Accu: 25.60
Epoch: [0][150/1225] Time: 0.145 (0.161) lr:0.010 Loss: 6.3949 (10.1102) iLoss: 5.7775 (6.6921) TLoss: 0.6174 (3.4181) Accu: 31.62
Epoch: [0][200/1225] Time: 0.144 (0.157) lr:0.010 Loss: 5.6413 (9.2617) iLoss: 5.0133 (6.5434) TLoss: 0.6280 (2.7183) Accu: 34.92
Epoch: [0][250/1225] Time: 0.145 (0.154) lr:0.010 Loss: 6.7509 (8.6793) iLoss: 6.1662 (6.3863) TLoss: 0.5846 (2.2930) Accu: 37.55
Epoch: [0][300/1225] Time: 0.145 (0.153) lr:0.010 Loss: 6.5356 (8.2504) iLoss: 5.9391 (6.2440) TLoss: 0.5965 (2.0064) Accu: 39.76
Epoch: [0][350/1225] Time: 0.145 (0.152) lr:0.010 Loss: 4.6654 (7.8957) iLoss: 4.1601 (